export const STUDENT = "סטודנט";
export const ADVANCED_CANDIDATE = "מועמד מתקדם";
export const INTERN = "מתמחה";
export const COMPANY_REPRESENTATIVE = "נציג חברה";
export const MENTOR = "מנטור";
export const PROGRAM_MANAGER = "מנהל תוכנית התמחות";
export const PROGRAM_COORDINATOR = "רכז תוכנית התמחות";
export const GUEST = "אורח";
export const SYSTEM_MANAGER = "מנהל מערכת";
